session_output cpu_regress.agarwal.220196.20_04_28_10_43_35_4103 {
	session_dir: "/home/grads/a/agarwal.220196/CSCE689_labs/final_project/CSCE-689-ProjectSpring20/project_release-master/project/sim/regression/cpu_regress.agarwal.220196.20_04_28_10_43_35_4103";
	original_session_dir: "/home/grads/a/agarwal.220196/CSCE689_labs/final_project/CSCE-689-ProjectSpring20/project_release-master/project/sim/regression/cpu_regress.agarwal.220196.20_04_28_10_43_35_4103";
	top_dir: "/home/grads/a/agarwal.220196/CSCE689_labs/final_project/CSCE-689-ProjectSpring20/project_release-master/project/sim/regression/cpu_regress.agarwal.220196.20_04_28_10_43_35_4103/..";
	vsof: "/home/grads/a/agarwal.220196/CSCE689_labs/final_project/CSCE-689-ProjectSpring20/project_release-master/project/sim/regression/cpu_regress.agarwal.220196.20_04_28_10_43_35_4103/cpu_regress.vsof";
	chain_id: "0";
	runs_in_session: "1";
	total_runs_in_session: "1";
	session_start_time: "1588088616";
	session_log_file: "/home/grads/a/agarwal.220196/CSCE689_labs/final_project/CSCE-689-ProjectSpring20/project_release-master/project/sim/regression/cpu_regress.agarwal.220196.20_04_28_10_43_35_4103/chain_0/vm_brun.log";
	parsed_vsif: "parsed_cpu_regress.agarwal.220196.20_04_28_10_43_35_4103.vsif";
	full_title: "cpu_regress";
	original_vsif: "/home/grads/a/agarwal.220196/CSCE689_labs/final_project/CSCE-689-ProjectSpring20/project_release-master/project/sim/run_vm_all.vsif";
	pre_session_script: <text> echo "pre_session_script" </text>;
	session_status: "in_progress";
}

run 1 {
	full_title: "cpu_regress/all_test/read_miss_icache";
	original_test_path: "___all_test___read_miss_icache";
	seed: "random";
	sv_seed: "1";
	e_seed: "random";
	pre_commands: "";
	run_script: <text>cd /home/grads/a/agarwal.220196/CSCE689_labs/final_project/CSCE-689-ProjectSpring20/project_release-master/project/sim ; irun -f run_vm.f +UVM_TESTNAME=read_miss_icache</text>;
	scan_script: "vm_scan.pl ius.flt shell.flt";
	timeout: "13000000";
	chain_id: "0";
	run_dir: "/home/grads/a/agarwal.220196/CSCE689_labs/final_project/CSCE-689-ProjectSpring20/project_release-master/project/sim/regression/cpu_regress.agarwal.220196.20_04_28_10_43_35_4103/chain_0/all_test/run_1";
	drm_job_name: "cpu_regress.agarwal.220196.20_04_28_10_43_35_4103_cpu_regress___all_test___read_miss_icache__run_1";
	job_status: "waiting";
	drm_job_status: "PROCESSING";
	propogate_pre_group_script: "";
	propogate_post_group_script: "";
	session_log_file: "/home/grads/a/agarwal.220196/CSCE689_labs/final_project/CSCE-689-ProjectSpring20/project_release-master/project/sim/regression/cpu_regress.agarwal.220196.20_04_28_10_43_35_4103/chain_0/vm_brun.log";
	vsif: "18@/home/grads/a/agarwal.220196/CSCE689_labs/final_project/CSCE-689-ProjectSpring20/project_release-master/project/sim/run_vm_all.vsif";
}

